### ISSUE TITLE
Upgrade to php-github-api ^3.0

### ISSUE THREAD

**Issue by hussainweb** [contrib-tracker/backend#10]
There might be code changes required. This upgrade is required to use PHP 8.0.

Instructions: https://github.com/KnpLabs/php-github-api/blob/master/UPGRADE-3.0.md

**Comment by gkapoor121212** [comment]
One of the development dependency of https://github.com/KnpLabs/php-github-api i.e Guzzle, is locked at version 7.0 but in Drupal, we will have support for Guzzle 7.0 only in Drupal 10 https://www.drupal.org/project/drupal/issues/3104353

**Comment by hussainweb** [comment]
@gkapoor121212, as you might have already seen, the package's dev dependency won't cause conflicts for us. And we are free to use any PSR implementation, not just Guzzle 7. This means it can work with Guzzle 6 with the `guzzlehttp/psr7` and `php-http/guzzle6-adapter` which are already used in Drupal.

**Comment by hussainweb** [comment]
It seems like the MR did the trick. I just saw a Github contribution get pulled in at https://contrib.axelerant.com/node/3523441.
