### ISSUE TITLE
Use social auth google settings to restrict domain instead of custom code.

### ISSUE THREAD

**Issue by gkapoor121212** [contrib-tracker/backend#15]
Currently, the users which login into system require an Axelerant Gmail ID and this condition has been added via the custom code in the `ct_users` module. We can remove the custom code and use configurations provided by the Social auth google module or google developer app settings.

**Comment by hussainweb** [comment]
Last I checked, Social Auth Google didn't have such options. We considered writing a module but it seemed too trivial and I just wrote the custom code. It's worth reconsidering all the options again.

**Comment by hussainweb** [comment]
We can't remove the code in ct_user yet as it is responsible for activating the user. Social Auth module has no feature to enable users created through Social Auth flow. It follows the Drupal configuration for new accounts and we can't remove admin verification for that as `/user/register` callback is still enabled.

**Comment by gkapoor121212** [comment]
@hussainweb This is the line of code that I thought should be changed  `if (preg_match('/.*@axelerant\\.com$/i', $user_email) > 0) {` as it is restricting login to only users with Axelerant ID. If that's not the case we can keep this issue closed.

**Comment by hussainweb** [comment]
Ah, your point is to make this generic and usable by orgs other than Axelerant?

**Comment by gkapoor121212** [comment]
@hussainweb Yes.

**Comment by hussainweb** [comment]
Understood, @gkapoor121212. I created #33 to handle this.
