### ISSUE TITLE
Easy to be access

### ISSUE THREAD

**Issue by rishabjasrotia** [contrib-tracker/backend#303]
Easy to be access

Password Policy should be improved to make it more secured.

@hussainweb 

![_20231117_105137](https://github.com/contrib-tracker/backend/assets/33950743/dbbe77fd-3e43-49d9-b7b3-4b53079031ac)

**Comment by hussainweb** [comment]
Thank you for reporting this. I have changed the password here but there is a deeper issue here and I'll investigate that. I'll close this for now.
